[project]
name = "esewa"
version = "0.1.0"
description = " A Python client for eSewa integration"
author = "Sahil Dahal"
github = "https://github.com/sahilverse"
license: "MIT"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []
